const C=window.PENGU_CONFIG;
const state={candles:{},price:null,ticker:null,trades:[],connected:false,lastPacket:0};
const $=id=>document.getElementById(id);
const fmt=(n,d=8)=>Number.isFinite(n)?n.toFixed(d):"—";
const pct=n=>Number.isFinite(n)?`${n>=0?"+":""}${n.toFixed(2)}%`:"—";
function priceDigits(p){if(!Number.isFinite(p))return 8;if(p>=1000)return 2;if(p>=1)return 4;if(p>=.1)return 5;return 8}
function setText(id,v){if($(id))$(id).textContent=v}
function ema(a,n){if(!a.length)return NaN;const k=2/(n+1);let e=a[0];for(let i=1;i<a.length;i++)e=a[i]*k+e*(1-k);return e}
function rsi(a,n=14){if(a.length<n+1)return 50;let g=0,l=0;for(let i=1;i<=n;i++){const d=a[i]-a[i-1];g+=Math.max(d,0);l+=Math.max(-d,0)}let ag=g/n,al=l/n;for(let i=n+1;i<a.length;i++){const d=a[i]-a[i-1];ag=(ag*(n-1)+Math.max(d,0))/n;al=(al*(n-1)+Math.max(-d,0))/n}return al===0?100:100-(100/(1+ag/al))}
function stats(tf){const a=state.candles[tf]||[],c=a.map(x=>x.c),v=a.map(x=>x.q),p=c.at(-1),e9=ema(c,9),e21=ema(c,21),avg=v.slice(-20).reduce((x,y)=>x+y,0)/(Math.min(20,v.length)||1);return{p,e9,e21,rsi:rsi(c),volRatio:avg?v.at(-1)/avg:1,ret3:c.length>3?(p/c.at(-4)-1)*100:0,ret10:c.length>10?(p/c.at(-11)-1)*100:0}}
function decision(){const a=stats("1m"),b=stats("5m"),c=stats("15m");let score=0,reasons=[];
if(b.p>b.e9&&b.e9>b.e21){score+=2;reasons.push(["5m trend","Bullish","good"])}else if(b.p<b.e9&&b.e9<b.e21){score-=2;reasons.push(["5m trend","Bearish","bad"])}else reasons.push(["5m trend","Mixed","warn"]);
if(c.p>c.e21){score++;reasons.push(["15m trend","Above EMA21","good"])}else{score--;reasons.push(["15m trend","Below EMA21","bad"])}
if(b.rsi>=72){score--;reasons.push(["5m RSI",b.rsi.toFixed(1)+" overbought","warn"])}else if(b.rsi<=35){score++;reasons.push(["5m RSI",b.rsi.toFixed(1)+" weak/oversold","good"])}else reasons.push(["5m RSI",b.rsi.toFixed(1)+" neutral","neutral"]);
if(a.volRatio>=1.5){if(a.ret3>0){score+=2;reasons.push(["Live volume","Buying expansion","good"])}else if(a.ret3<0){score-=2;reasons.push(["Live volume","Selling expansion","bad"])}}
if(b.ret10>2){score++;reasons.push(["Momentum",pct(b.ret10)+" / 10m","good"])}else if(b.ret10<-2){score--;reasons.push(["Momentum",pct(b.ret10)+" / 10m","bad"])}else reasons.push(["Momentum",pct(b.ret10)+" / 10m","neutral"]);
let d="HOLD / WATCH",cl="neutral";if(score>=4){d="MOMENTUM UP";cl="good"}else if(score<=-3){d="EXIT RISK";cl="bad"}else if(score<=-1){d="CAUTION";cl="warn"}return{score,d,cl,reasons,a,b,c}}
function render(){if(!state.price)return;const d=decision(),p=state.price,t=state.ticker;setText("price",`$${fmt(p,priceDigits(p))}`);setText("change",t?`${pct(Number(t.r))} • 24h range $${fmt(Number(t.l),priceDigits(p))} — $${fmt(Number(t.h),priceDigits(p))}`:"Live");setText("decision",d.d);if($("decision"))$("decision").className=`decision ${d.cl}`;setText("confidence",`Score ${d.score>=0?"+":""}${d.score} • rule-based signal`);setText("volume",t?Number(t.q).toLocaleString(undefined,{maximumFractionDigits:0}):"—");const buys=state.trades.filter(x=>x.s==="buy").reduce((a,x)=>a+x.v,0),sells=state.trades.filter(x=>x.s==="sell").reduce((a,x)=>a+x.v,0);setText("flow",buys+sells?`${((buys/(buys+sells))*100).toFixed(0)}% buy`:"—");setText("flowSub",`${state.trades.length} recent trades`);setText("rsi1",d.a.rsi.toFixed(1));setText("rsi5",d.b.rsi.toFixed(1));setText("ema9",fmt(d.b.e9,priceDigits(p)));setText("ema21",fmt(d.b.e21,priceDigits(p)));setText("ema15",fmt(d.c.e21,priceDigits(p)));setText("volRatio",`x${d.a.volRatio.toFixed(2)}`);if($("signals"))$("signals").innerHTML=d.reasons.map(x=>`<div class="signal"><span class="name">${x[0]}</span><b class="${x[2]}">${x[1]}</b></div>`).join("");renderLevels(p);drawChart()}
function renderLevels(p){const e=C.entryPrice;if(!e){["entry","stop","tp1","tp2","pnl"].forEach(id=>setText(id,"Not set"));return}setText("entry",`$${fmt(e,priceDigits(e))}`);setText("stop",`$${fmt(e*(1-C.stopLossPct/100),priceDigits(e))}`);setText("tp1",`$${fmt(e*(1+C.tp1Pct/100),priceDigits(e))}`);setText("tp2",`$${fmt(e*(1+C.tp2Pct/100),priceDigits(e))}`);const x=(p/e-1)*100;setText("pnl",pct(x));if($("pnl"))$("pnl").className=x>=0?"good":"bad"}
function drawChart(){const cv=$("chart");if(!cv)return;const r=cv.getBoundingClientRect(),d=devicePixelRatio||1;cv.width=r.width*d;cv.height=r.height*d;const ctx=cv.getContext("2d");ctx.scale(d,d);const w=r.width,h=r.height;ctx.clearRect(0,0,w,h);const a=(state.candles["5m"]||[]).slice(-70);if(a.length<2)return;const lo=Math.min(...a.map(x=>x.l)),hi=Math.max(...a.map(x=>x.h)),pad=18,x=i=>pad+i/(a.length-1)*(w-pad*2),y=v=>h-pad-(v-lo)/(hi-lo||1)*(h-pad*2);ctx.strokeStyle="#202836";for(let i=0;i<5;i++){const yy=pad+i*(h-pad*2)/4;ctx.beginPath();ctx.moveTo(0,yy);ctx.lineTo(w,yy);ctx.stroke()}ctx.beginPath();a.forEach((c,i)=>i?ctx.lineTo(x(i),y(c.c)):ctx.moveTo(x(i),y(c.c)));ctx.strokeStyle="#70a7ff";ctx.lineWidth=2;ctx.stroke()}
function connect(){const url=C.backendUrl.replace(/\/$/,"")+"/stream";const es=new EventSource(url);es.onopen=()=>{state.connected=true;setText("connection","Live");if($("dot"))$("dot").style.background="var(--green)"};es.onmessage=e=>{const m=JSON.parse(e.data);Object.assign(state,m);state.connected=true;render();if($("latency"))setText("latency",`${Math.max(0,Date.now()-state.lastPacket)}ms`)};es.onerror=()=>{state.connected=false;setText("connection","Reconnecting…");if($("dot"))$("dot").style.background="var(--yellow")}} 
connect();
